language: python

# https://docs.travis-ci.com/user/trusty-ci-environment
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - graphviz

# https://docs.travis-ci.com/user/languages/python/
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

script:
- python tests/test.py

# https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: jrfonseca
  password:
    secure: CUjvaGfHLJFZKjiDnOEv+bPlze0kqQRzs2SZbooeeqW/MS2URVUaaThabF8c3KPl//V2WrFyAaI6vqIHe78fEvTZKerKHhMfjIlP//DlbwkQoXIuHLHeFuIGo3WsZLUqOdOficEArDK7kGM4LdWvDzQa1SHktvGbZyojISGv2tM=
  on:
    tags: true
    distributions: sdist
    repo: jrfonseca/gprof2dot
  skip_upload_docs: true
