language: python

sudo: false

addons:
  apt:
    packages:
    - graphviz

# https://docs.travis-ci.com/user/languages/python/
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

script:
- python tests/test.py
