language: python

# https://docs.travis-ci.com/user/trusty-ci-environment
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - graphviz

# https://docs.travis-ci.com/user/languages/python/
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

script:
- python tests/test.py

# https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: jrfonseca
  password:
    secure: HAPllYFYXrSl5IPMIoWHCTuk6rxxqoHDZWudtctiVxBGlaBftya08nFi+jfWHZOE3cofoqnkXUV+9qtMG9aLW8wVtZeABy33KQe2MPppn3dNFN/UKKskXBsFpSeFy8xAwwcWou1okrg9kFfZpxwb272e0MHrtMsXjNmpodrUAhM=
  on:
    tags: true
    distributions: sdist
    repo: jrfonseca/gprof2dot
  skip_upload_docs: true
